import Head from "next/head";
import {
  Header,
  Wrapper,
  SectionAbout,
  SectionAnalyze,
  SectionStrategy,
  SectionWhyUs,
  SectionTeam,
} from "../components/";

export default function Home() {
  return (
    <>
      <Head>
        <title>Sandbox</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Wrapper>
        <Header />
        <SectionAbout />
        <SectionAnalyze />
        <SectionStrategy />
        <SectionWhyUs />
        <SectionTeam />
      </Wrapper>
    </>
  );
}
